# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx1024m -XX:MaxPermSize=256m
    
    steps:

      - add_ssh_keys

      - run:
          name: Set ssh
          command: echo 'login.toolforge.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFnJSjCGW7kli+cdgtmndPAl4xLZNc9uqP9KWlsnVDqr8yQ2RkR5ACbXe6XZ+dS09Wc9ulOmGTOwCImMi9Fho78=' >> ~/.ssh/known_hosts

      - run:
          name: Open tunnel to db
          command: ssh -f -v -N -L 3306:s1.analytics.db.svc.eqiad.wmflabs:3306 ${DEPLOY_USER}@login.toolforge.org

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn clean package dependency:go-offline ${BUILD_PROPERTIES}

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Creates a backup of currently running server .jar and replaces it with newer version
      - deploy:
          name: .jar upload
          command: |
            ssh -v ${DEPLOY_USER}@login.toolforge.org "cp /data/project/mw2sparql/mwontop-${TARGET_VERSION}.jar /data/project/mw2sparql/mwontop-${TARGET_VERSION}.old"
            scp -r ~/repo/target/mwontop-${TARGET_VERSION}.jar ${DEPLOY_USER}@login.toolforge.org:/data/project/mw2sparql/mwontop-${TARGET_VERSION}.jar

      # Calls restart.sh on the remote server
      - deploy:
          name: Server restart
          command: ssh -v ${DEPLOY_USER}@login.toolforge.org "become mw2sparql webservice restart"
